import { StyleSheet } from 'react-native';
import { colors, radii, spacing, typography } from '@daloa/ui';

export const shopSettingsStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg.DEFAULT },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing[3],
    paddingBottom: spacing[2],
    backgroundColor: colors.bg.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.subtle,
    gap: spacing[2],
  },
  backBtn: { width: 36, height: 36, borderRadius: radii.md, alignItems: 'center', justifyContent: 'center' },
  saveBtn: { paddingHorizontal: spacing[3], paddingVertical: 6 },
  scrollContent: { padding: spacing[4], gap: spacing[4] },
  sectionCard: {
    backgroundColor: colors.bg.surface,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.border.DEFAULT,
    padding: spacing[4],
    gap: spacing[3],
  },
  districtSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border.DEFAULT,
    borderRadius: radii.lg,
    padding: spacing[3],
    gap: 8,
    backgroundColor: colors.bg.subtle,
  },
  textArea: { height: 72, textAlignVertical: 'top' },
  colorSection: { gap: spacing[2] },
  colorLabelRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  colorRow: { flexDirection: 'row', gap: spacing[3] },
  colorCircle: { width: 34, height: 34, borderRadius: radii.full, alignItems: 'center', justifyContent: 'center' },
  colorActive: { borderWidth: 3, borderColor: '#000' },
  switchRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing[3] },
  codDeliverersBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: spacing[3],
    paddingVertical: 8,
    borderRadius: radii.md,
    borderWidth: 1,
  },
  codDeliverersText: { fontFamily: typography.families.extrabold },
  feedbackCard: { flexDirection: 'row', alignItems: 'center', gap: 8, padding: spacing[3], borderRadius: radii.lg },
  feedbackSuccess: { backgroundColor: colors.status.successLight },
  feedbackError: { backgroundColor: colors.status.errorLight },
  flex1: { flex: 1 },
  slugFeedbackRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: -4 },
});
